name: formaster
description: Kit for create form
version: 0.1.0
homepage: https://github.com/iadept/flutter_formaster
repository: https://github.com/iadept/flutter_formaster

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
